name: 'First action'
description: 'Echo an output'
# inputs:
  # who-to-greet:  # id of input
    # description: 'Who to greet'
    # required: true
    # default: 'World'
# outputs:
  # time: # id of output
    # description: 'The time we greeted you'

# TODO: Add commented out examples of jobs in action

runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
    # - ${{ inputs.who-to-greet }}